sudo: false
language: python
python: 2.7
env:
  global:
  - MULLED_NAMESPACE=jmchiltonorg
  - GITHUB_USER=dockerhub-toolshed
  - secure: VDDSnaojmTBGz0rKWibM6Kuz9YdhVKtwQZ6UqouU8DUiFjSqf8/JApPxfvxkEJO0H5y/8FnaQwcGVkLWchgBjU2dLZIDpQSix3lfmuffd/OLfWA7BtzuT5pYoz2KwiZcis29vDCqE2vyXBnd0FqsSdq/aIik1vhiVp/yJVpD3beAFyVHawcnqcSswW525NCeJPhKv+QF6UAwwGXF/xgrx9E5F59Q880Q1HLRStsuQHGrgVuc3fk0RiC7DeD7jVd1lBdNodTKEckj4HdbL9WAiNGJ2hVhUtsaqEvA9hd+0Cr7sIOOYygZVA9IPp8xHZdZYpOJ5ruC66Ba+d7+XfIjfNI1qBjP76lAAZK55yzxR7SUvQpLynpB5sodjwQrZGI4PEmsFFgHE227Q5ox+2dIcfHy02aNP3Qij+iTOmKwFhi6qeHKa5kC7GyN7CrQlM8MauF/zNwX3OOu9ayNs1Nzowj1Ys7N9wTPDkZbH7R7xNobW4eCHk9MXjGdPCbhj4RSsZ027Kr2MsKo9q71bnU/M1d9Q58Hyw8mRVgu2JFB4VbFJiFHaJgoIWW95pDyi0dvoZJSjzpdC/HlZw/dRHkhZK+EXaMxXouh8//4GaniUXW4bEhEADK3RsgCTat5FmH1CULJQ6OdN/3fmbRRclkSIJkqYfYHYIv4gRMPcH9nMm0=
script:
- bash monitor.sh
