language: python
python: 2.7
env:
  global:
  - MULLED_NAMESPACE=jmchiltonorg
  - GITHUB_USER=dockerhub-planemo
  # Next up GITHUB_PASSWORD
  - secure: fEBVFTteXbVoVjJV04DmFpQHBDjivpqqM7yD6VYIcMKhXqDwBQrrzCdA/lz95RFsPxuINMLkCwhHqItPrxe24tuuXd4Ij17laXhT98QONVG6KvKn5e0w5UkO2kGWFtYJqgwinMyZicIa3yK+u2py6nbsOBU3lmYjiDdHkw2a5bGuicKFDwfsitDsg7t/QIDKP8IDTUU1iOdgCJfe/x94e4UuvIHcALw+ZPUuyJfwMh908f5yhikvpYLtiwDhAU8cHiERKnyxJNQfScYB5bbCzVB90EdSK/ws6icOt6xMkoB65sytoA373JIubPWu/HtMrckFoeFhpcqSQOmKIu+ZGFd692s8q3VpXgCAa1XuCKNs2FzeR/G314ckF8gM5GUDLRAW7RyQ9l0UbDvMwJ0lJLNpFW5xElyYHTMR3JwGfW8GnrxupsuxmMUbF7hffiaITUNb6PRmcP3V2vqLtM43rG9Pt/QZUtwNEnqGhcsmCWPvgxaj4yQD5oo5cuueJVDjw4CECHsczHKislUzrajK0xCnOFh4uqR6l/oPQZMKZQt0CXCH8gfNasyDfKBl/9DA6bpda/gdsnNuRFxBIl6VROw3jvklvirXBuzvwEXNBW8j6oV+6oYGbUFTT+4me+8E6yq7w7zww8RUYK2QltntRuvPl9MLptE9hbvAYPEhZNw=
before_install:
- pip install PyGithub
#- pip install planemo
- pip install https://github.com/jmchilton/planemo/archive/mulled_register.zip # TODO: galaxy-lib

script:
- ./monitor.sh

