sudo: false
language: python
python: 2.7
env:
  global:
  - MULLED_NAMESPACE=jmchiltonorg
  - GITHUB_USER=dockerhub-planemo
  - secure: OkgLSRovPeREdTOv9iCXbFiCz2LYbm4+LnZMX8iIQTxRx05gai6XED255HfbWsb0hBv91hokPKeKgmbRR2aaSvYYcvlDN0swZoYy+yU4S+k9+YVP7eljaPUyGtC7hZYm/JJaV4HeHlLXvzxI5K7uNlazovVXc2uSXaO+onpqN+6obz/uJaJZBhZPeiQV5BhHlJzocJ/Hdut3fpJn9mAqmlpeg+KiOkVWA21bPbeH1o8P+FXDeQjE29Qdfsgn7OPX350aO9ZO7DoIqhqs5faEP+lgQwkDHcmuj4xa6qZIUJZg/vwLovYdoapClS6IHp0L3FPeyrdl7b/5i334dowLPMfsvhAw0VpKurDjmZCdXmB5w14FrTCBnN5vtz2cUsGp9LwHtTadjqem1NgpGxiAyQTAgQ9+kMkONdJTUlPvELshGLtxr4Nc7id6Vk+Mt3Hz2c9BZIvjG44OMS8OnnDCJXInNyzg4GXCxGJqWrzqfb9XzrVIoE1TgN0uteOfchxCITmDxRHTuTrL+z9Q+pFORByuD14jJCPl8ukpOavHETYK7u1hE5BNej43fP9jglE5IVhSHFJ3ck15MNDkwBjU08bmMbv0gqmFm8lvHgwhhAKSD/Mu5mdVEaBHMMN9nZwOsm1uaJcHKlfTMRFY66aSL4kuAUqrtYmsdF2Jb8yvlPQ=
before_install:
- pip install -U pip
- pip install PyGithub
- pip install https://github.com/jmchilton/planemo/archive/mulled_register.zip
script:
- ls && bash monitor.sh
